import { createFileRoute, Link } from "@tanstack/react-router";
import { ClipboardList, Eye, MessageSquare, PlayCircle } from "lucide-react";
import { useAuth } from "@/lib/auth";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "About — MIRA Reviewer" },
      {
        name: "description",
        content:
          "Overview of the MIRA review process for parent and expert reviewers.",
      },
      { name: "robots", content: "noindex" },
    ],
  }),
  component: AboutPage,
});

function AboutPage() {
  const { role } = useAuth();

  return (
    <main className="mx-auto max-w-6xl px-6 py-10">
      <header className="mb-8">
        <h1 className="text-3xl font-semibold tracking-tight text-foreground">
          Welcome to MIRA
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Motivational Interviewing Response Assessment — a research study
          comparing AI-generated and human responses to parent concerns about
          HPV vaccination.
        </p>
      </header>

      <div className="grid gap-8 lg:grid-cols-[1.1fr_1fr]">
        <section className="space-y-6">
          <div className="rounded-xl border border-border bg-card p-6">
            <h2 className="text-lg font-semibold text-foreground">
              About the review process
            </h2>
            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              You will be shown short dialogues between a parent and an
              interviewer discussing the HPV vaccine. For each dialogue you'll
              see two possible responses to the parent's most recent concern,
              labeled Response A and Response B.
            </p>
            <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
              One response was written by a human interviewer, the other was
              generated by MIRA. You will not be told which is which — the
              order is randomized for every review.
            </p>
          </div>

          <ol className="space-y-4">
            <Step
              icon={Eye}
              title="1. Read the dialogue"
              body="Review the parent's concern and the exchange leading up to it. Take a moment to understand the context before evaluating either response."
            />
            <Step
              icon={ClipboardList}
              title={
                role === "expert"
                  ? "2. Rate each response"
                  : "2. Rate each response"
              }
              body={
                role === "expert"
                  ? "Score both responses for medical safety, accuracy, and relevance. Flag anything that could mislead a parent."
                  : "Rate how appropriate, clear, responsible, and empathic each response feels from a parent's perspective."
              }
            />
            <Step
              icon={MessageSquare}
              title="3. Pick a preferred response"
              body="Choose the response you prefer overall (or mark them as too similar) and add a brief comment explaining your choice."
            />
          </ol>

          <div className="rounded-xl border border-primary/20 bg-primary-soft/40 p-5">
            <h3 className="text-sm font-semibold text-primary">
              Ready to begin?
            </h3>
            <p className="mt-1 text-sm text-foreground/80">
              You can revisit these instructions any time from the About link
              in the top navigation.
            </p>
            <Link
              to="/"
              className="mt-4 inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90"
            >
              <PlayCircle className="h-4 w-4" />
              Begin reviewing
            </Link>
          </div>
        </section>

        <aside className="space-y-3">
          <h2 className="text-sm font-semibold text-foreground">
            Watch: MIRA overview
          </h2>
          <div className="aspect-video overflow-hidden rounded-xl border border-border bg-black shadow-sm">
            <iframe
              width="560"
              height="315"
              src="https://www.youtube-nocookie.com/embed/URiKA7CKtfc?si=D3fh3aYnre-xUg4y"
              title="YouTube video player"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
              referrerPolicy="strict-origin-when-cross-origin"
              allowFullScreen
              className="h-full w-full"
            />
          </div>
          <p className="text-xs text-muted-foreground">
            A short introduction to the study and how your reviews are used.
          </p>
        </aside>
      </div>
    </main>
  );
}

function Step({
  icon: Icon,
  title,
  body,
}: {
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  body: string;
}) {
  return (
    <li className="flex gap-4 rounded-xl border border-border bg-card p-5">
      <span className="mt-0.5 flex h-9 w-9 flex-none items-center justify-center rounded-md bg-primary-soft text-primary">
        <Icon className="h-4 w-4" />
      </span>
      <div>
        <h3 className="text-sm font-semibold text-foreground">{title}</h3>
        <p className="mt-1 text-sm text-muted-foreground">{body}</p>
      </div>
    </li>
  );
}
