import { createFileRoute } from "@tanstack/react-router";
import { DialogueReview } from "@/components/mira/DialogueReview";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "MIRA — Motivational Interviewing Response Assessment" },
      {
        name: "description",
        content:
          "Review and compare motivational interviewing responses generated by human and AI sources.",
      },
      {
        property: "og:title",
        content: "MIRA — Motivational Interviewing Response Assessment",
      },
      {
        property: "og:description",
        content:
          "A research review interface for evaluating motivational interviewing dialogue responses.",
      },
    ],
  }),
  component: DialogueReview,
});
