/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDocsIndexRouteImport } from './routes/api-docs.index'
import { Route as ReviewersReviewerIdRouteImport } from './routes/reviewers.$reviewerId'
import { Route as ApiDocsUsersRouteImport } from './routes/api-docs.users'
import { Route as ApiDocsTranscriptsRouteImport } from './routes/api-docs.transcripts'
import { Route as ApiDocsSchemaRouteImport } from './routes/api-docs.schema'
import { Route as ApiDocsReviewsRouteImport } from './routes/api-docs.reviews'
import { Route as ApiDocsProgressRouteImport } from './routes/api-docs.progress'
import { Route as ApiDocsMetricsRouteImport } from './routes/api-docs.metrics'
import { Route as ApiDocsDialoguesRouteImport } from './routes/api-docs.dialogues'
import { Route as ApiDocsAuthRouteImport } from './routes/api-docs.auth'
import { Route as ApiDocsAccountRouteImport } from './routes/api-docs.account'
import { Route as ReviewsReviewerIdItemIdRouteImport } from './routes/reviews.$reviewerId.$itemId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsIndexRoute = ApiDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiDocsRoute,
} as any)
const ReviewersReviewerIdRoute = ReviewersReviewerIdRouteImport.update({
  id: '/reviewers/$reviewerId',
  path: '/reviewers/$reviewerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsUsersRoute = ApiDocsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ApiDocsRoute,
} as any)
const ApiDocsTranscriptsRoute = ApiDocsTranscriptsRouteImport.update({
  id: '/transcripts',
  path: '/transcripts',
  getParentRoute: () => ApiDocsRoute,
} as any)
const ApiDocsSchemaRoute = ApiDocsSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => ApiDocsRoute,
} as any)
const ApiDocsReviewsRoute = ApiDocsReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ApiDocsRoute,
} as any)
const ApiDocsProgressRoute = ApiDocsProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ApiDocsRoute,
} as any)
const ApiDocsMetricsRoute = ApiDocsMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => ApiDocsRoute,
} as any)
const ApiDocsDialoguesRoute = ApiDocsDialoguesRouteImport.update({
  id: '/dialogues',
  path: '/dialogues',
  getParentRoute: () => ApiDocsRoute,
} as any)
const ApiDocsAuthRoute = ApiDocsAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => ApiDocsRoute,
} as any)
const ApiDocsAccountRoute = ApiDocsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ApiDocsRoute,
} as any)
const ReviewsReviewerIdItemIdRoute = ReviewsReviewerIdItemIdRouteImport.update({
  id: '/reviews/$reviewerId/$itemId',
  path: '/reviews/$reviewerId/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/users': typeof UsersRoute
  '/api-docs/account': typeof ApiDocsAccountRoute
  '/api-docs/auth': typeof ApiDocsAuthRoute
  '/api-docs/dialogues': typeof ApiDocsDialoguesRoute
  '/api-docs/metrics': typeof ApiDocsMetricsRoute
  '/api-docs/progress': typeof ApiDocsProgressRoute
  '/api-docs/reviews': typeof ApiDocsReviewsRoute
  '/api-docs/schema': typeof ApiDocsSchemaRoute
  '/api-docs/transcripts': typeof ApiDocsTranscriptsRoute
  '/api-docs/users': typeof ApiDocsUsersRoute
  '/reviewers/$reviewerId': typeof ReviewersReviewerIdRoute
  '/api-docs/': typeof ApiDocsIndexRoute
  '/reviews/$reviewerId/$itemId': typeof ReviewsReviewerIdItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/users': typeof UsersRoute
  '/api-docs/account': typeof ApiDocsAccountRoute
  '/api-docs/auth': typeof ApiDocsAuthRoute
  '/api-docs/dialogues': typeof ApiDocsDialoguesRoute
  '/api-docs/metrics': typeof ApiDocsMetricsRoute
  '/api-docs/progress': typeof ApiDocsProgressRoute
  '/api-docs/reviews': typeof ApiDocsReviewsRoute
  '/api-docs/schema': typeof ApiDocsSchemaRoute
  '/api-docs/transcripts': typeof ApiDocsTranscriptsRoute
  '/api-docs/users': typeof ApiDocsUsersRoute
  '/reviewers/$reviewerId': typeof ReviewersReviewerIdRoute
  '/api-docs': typeof ApiDocsIndexRoute
  '/reviews/$reviewerId/$itemId': typeof ReviewsReviewerIdItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/users': typeof UsersRoute
  '/api-docs/account': typeof ApiDocsAccountRoute
  '/api-docs/auth': typeof ApiDocsAuthRoute
  '/api-docs/dialogues': typeof ApiDocsDialoguesRoute
  '/api-docs/metrics': typeof ApiDocsMetricsRoute
  '/api-docs/progress': typeof ApiDocsProgressRoute
  '/api-docs/reviews': typeof ApiDocsReviewsRoute
  '/api-docs/schema': typeof ApiDocsSchemaRoute
  '/api-docs/transcripts': typeof ApiDocsTranscriptsRoute
  '/api-docs/users': typeof ApiDocsUsersRoute
  '/reviewers/$reviewerId': typeof ReviewersReviewerIdRoute
  '/api-docs/': typeof ApiDocsIndexRoute
  '/reviews/$reviewerId/$itemId': typeof ReviewsReviewerIdItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-docs'
    | '/dashboard'
    | '/generate'
    | '/login'
    | '/progress'
    | '/users'
    | '/api-docs/account'
    | '/api-docs/auth'
    | '/api-docs/dialogues'
    | '/api-docs/metrics'
    | '/api-docs/progress'
    | '/api-docs/reviews'
    | '/api-docs/schema'
    | '/api-docs/transcripts'
    | '/api-docs/users'
    | '/reviewers/$reviewerId'
    | '/api-docs/'
    | '/reviews/$reviewerId/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/generate'
    | '/login'
    | '/progress'
    | '/users'
    | '/api-docs/account'
    | '/api-docs/auth'
    | '/api-docs/dialogues'
    | '/api-docs/metrics'
    | '/api-docs/progress'
    | '/api-docs/reviews'
    | '/api-docs/schema'
    | '/api-docs/transcripts'
    | '/api-docs/users'
    | '/reviewers/$reviewerId'
    | '/api-docs'
    | '/reviews/$reviewerId/$itemId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api-docs'
    | '/dashboard'
    | '/generate'
    | '/login'
    | '/progress'
    | '/users'
    | '/api-docs/account'
    | '/api-docs/auth'
    | '/api-docs/dialogues'
    | '/api-docs/metrics'
    | '/api-docs/progress'
    | '/api-docs/reviews'
    | '/api-docs/schema'
    | '/api-docs/transcripts'
    | '/api-docs/users'
    | '/reviewers/$reviewerId'
    | '/api-docs/'
    | '/reviews/$reviewerId/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiDocsRoute: typeof ApiDocsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  GenerateRoute: typeof GenerateRoute
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  UsersRoute: typeof UsersRoute
  ReviewersReviewerIdRoute: typeof ReviewersReviewerIdRoute
  ReviewsReviewerIdItemIdRoute: typeof ReviewsReviewerIdItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs/': {
      id: '/api-docs/'
      path: '/'
      fullPath: '/api-docs/'
      preLoaderRoute: typeof ApiDocsIndexRouteImport
      parentRoute: typeof ApiDocsRoute
    }
    '/reviewers/$reviewerId': {
      id: '/reviewers/$reviewerId'
      path: '/reviewers/$reviewerId'
      fullPath: '/reviewers/$reviewerId'
      preLoaderRoute: typeof ReviewersReviewerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs/users': {
      id: '/api-docs/users'
      path: '/users'
      fullPath: '/api-docs/users'
      preLoaderRoute: typeof ApiDocsUsersRouteImport
      parentRoute: typeof ApiDocsRoute
    }
    '/api-docs/transcripts': {
      id: '/api-docs/transcripts'
      path: '/transcripts'
      fullPath: '/api-docs/transcripts'
      preLoaderRoute: typeof ApiDocsTranscriptsRouteImport
      parentRoute: typeof ApiDocsRoute
    }
    '/api-docs/schema': {
      id: '/api-docs/schema'
      path: '/schema'
      fullPath: '/api-docs/schema'
      preLoaderRoute: typeof ApiDocsSchemaRouteImport
      parentRoute: typeof ApiDocsRoute
    }
    '/api-docs/reviews': {
      id: '/api-docs/reviews'
      path: '/reviews'
      fullPath: '/api-docs/reviews'
      preLoaderRoute: typeof ApiDocsReviewsRouteImport
      parentRoute: typeof ApiDocsRoute
    }
    '/api-docs/progress': {
      id: '/api-docs/progress'
      path: '/progress'
      fullPath: '/api-docs/progress'
      preLoaderRoute: typeof ApiDocsProgressRouteImport
      parentRoute: typeof ApiDocsRoute
    }
    '/api-docs/metrics': {
      id: '/api-docs/metrics'
      path: '/metrics'
      fullPath: '/api-docs/metrics'
      preLoaderRoute: typeof ApiDocsMetricsRouteImport
      parentRoute: typeof ApiDocsRoute
    }
    '/api-docs/dialogues': {
      id: '/api-docs/dialogues'
      path: '/dialogues'
      fullPath: '/api-docs/dialogues'
      preLoaderRoute: typeof ApiDocsDialoguesRouteImport
      parentRoute: typeof ApiDocsRoute
    }
    '/api-docs/auth': {
      id: '/api-docs/auth'
      path: '/auth'
      fullPath: '/api-docs/auth'
      preLoaderRoute: typeof ApiDocsAuthRouteImport
      parentRoute: typeof ApiDocsRoute
    }
    '/api-docs/account': {
      id: '/api-docs/account'
      path: '/account'
      fullPath: '/api-docs/account'
      preLoaderRoute: typeof ApiDocsAccountRouteImport
      parentRoute: typeof ApiDocsRoute
    }
    '/reviews/$reviewerId/$itemId': {
      id: '/reviews/$reviewerId/$itemId'
      path: '/reviews/$reviewerId/$itemId'
      fullPath: '/reviews/$reviewerId/$itemId'
      preLoaderRoute: typeof ReviewsReviewerIdItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiDocsRouteChildren {
  ApiDocsAccountRoute: typeof ApiDocsAccountRoute
  ApiDocsAuthRoute: typeof ApiDocsAuthRoute
  ApiDocsDialoguesRoute: typeof ApiDocsDialoguesRoute
  ApiDocsMetricsRoute: typeof ApiDocsMetricsRoute
  ApiDocsProgressRoute: typeof ApiDocsProgressRoute
  ApiDocsReviewsRoute: typeof ApiDocsReviewsRoute
  ApiDocsSchemaRoute: typeof ApiDocsSchemaRoute
  ApiDocsTranscriptsRoute: typeof ApiDocsTranscriptsRoute
  ApiDocsUsersRoute: typeof ApiDocsUsersRoute
  ApiDocsIndexRoute: typeof ApiDocsIndexRoute
}

const ApiDocsRouteChildren: ApiDocsRouteChildren = {
  ApiDocsAccountRoute: ApiDocsAccountRoute,
  ApiDocsAuthRoute: ApiDocsAuthRoute,
  ApiDocsDialoguesRoute: ApiDocsDialoguesRoute,
  ApiDocsMetricsRoute: ApiDocsMetricsRoute,
  ApiDocsProgressRoute: ApiDocsProgressRoute,
  ApiDocsReviewsRoute: ApiDocsReviewsRoute,
  ApiDocsSchemaRoute: ApiDocsSchemaRoute,
  ApiDocsTranscriptsRoute: ApiDocsTranscriptsRoute,
  ApiDocsUsersRoute: ApiDocsUsersRoute,
  ApiDocsIndexRoute: ApiDocsIndexRoute,
}

const ApiDocsRouteWithChildren =
  ApiDocsRoute._addFileChildren(ApiDocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiDocsRoute: ApiDocsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  GenerateRoute: GenerateRoute,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  UsersRoute: UsersRoute,
  ReviewersReviewerIdRoute: ReviewersReviewerIdRoute,
  ReviewsReviewerIdItemIdRoute: ReviewsReviewerIdItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
