type Props = {
  current: number;
  total: number;
};

export function Header({ current, total }: Props) {
  return (
    <header className="border-b border-border bg-card">
      <div className="mx-auto max-w-6xl px-6 py-8">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <div className="flex items-center gap-3">
              <h1 className="text-3xl font-semibold tracking-tight text-primary">
                MIRA
              </h1>
              <span className="rounded-full bg-primary-soft px-2.5 py-0.5 text-xs font-medium text-primary">
                Research preview
              </span>
            </div>
            <p className="mt-1 text-base font-medium text-foreground">
              Motivational Interviewing Response Assessment
            </p>
            <p className="mt-2 max-w-2xl text-sm text-muted-foreground">
              Review and compare motivational interviewing responses generated by
              human and AI sources.
            </p>
          </div>
          <div className="flex flex-col items-start gap-1 sm:items-end">
            <span className="text-xs uppercase tracking-wide text-muted-foreground">
              Progress
            </span>
            <span className="rounded-md border border-border bg-background px-3 py-1.5 text-sm font-medium text-foreground">
              Review {current} of {total}
            </span>
          </div>
        </div>
      </div>
    </header>
  );
}
